substitutions:
  name: bluetooth-hub
esphome:
  name: ${name}-${location}
  friendly_name: "${name} ${location}"
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

api:
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    - esp32_ble_tracker.stop_scan:

improv_serial:
esp32_ble_tracker:
  scan_parameters:
    continuous: false
    active: true
    interval: 1000ms # default 320ms. Time spent per adv channel
    window: 900ms # default 30ms. Time spent listening during interval.
bluetooth_proxy:
  active: true
