wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  ap:
    password: !secret admin_password
    ssid: ${name}-${location}

ota:
  password: !secret admin_password

api:
logger:
