substitutions:
  name: bluetooth-hub
  
esphome:
  name: ${name}-${location}

esp32:
  board: wemos_d1_mini32

captive_portal:
  
uart:
  rx_pin: GPIO10
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "${location} Particulate Matter 2.5µm Concentration"
