substitutions:
  mac_1: C4:7C:8D:6B:F6:07
  mac_2: C4:7C:8D:6B:F5:6C
  mac_3: C4:7C:8D:6B:F3:8A
  mac_4: C4:7C:8D:6B:F3:91
  mac_5: C4:7C:8D:6C:12:83
  mac_6: C4:7C:8D:6B:B2:F8
  mac_7: C4:7C:8D:6B:F5:CC #fake
  mac_8: C4:7C:8D:6B:F5:CB #fake
  mac_9: C4:7C:8D:6C:1D:E8
  mac_10: C4:7C:8D:6B:F5:C0
