substitutions:
  name: shelly-1

esphome:
  name: ${name}-${location}
  platform: ESP8266
  board: esp01_1m

captive_portal:

switch:
  - platform: gpio
    name: ${name}-${location}
    pin: GPIO4
    id: shelly_relay
    # after reboot, keep the relay off. this prevents light turning on after a power outage
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    name: ${name}-${location}
    pin:
      number: GPIO5
    # small delay to prevent debouncing
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
        then:
          - if:
              condition:
                and:
                  - wifi.connected:
                  - api.connected:
              # toggle smart light if wifi and api are connected and relay is on
              then:
              # else, toggle relay
              else:
                - switch.toggle: shelly_relay
    id: button