# lovelace_gen
entity: sensor.dagdeel
default_url: /local/images/wallpapers/pexels-victor-freitas-600114.jpg
state_url:
  ochtend-begin: /local/images/wallpapers/02-Mid-Morning.png
  ochtend-mid: /local/images/wallpapers/03-Late-Morning.png
  ochtend-eind: /local/images/wallpapers/04-Early-Afternoon.png
  middag-begin: /local/images/wallpapers/05-Mid-Afternoon.png
  middag-mid: /local/images/wallpapers/06-Late-Afternoon.png
  middag-eind: /local/images/wallpapers/07-Early-Evening.png
  avond-begin: /local/images/wallpapers/08-Mid-Evening.png
  avond-mid: /local/images/wallpapers/09-Late-Evening.png
  avond-eind: /local/images/wallpapers/10-Early-Night.png
  nacht-begin: /local/images/wallpapers/11-Mid-Night.png
  nacht-mid: /local/images/wallpapers/12-Late-Night.png
  nacht-eind: /local/images/wallpapers/01-Early-Morning.png
views:
  - path: weather
    config:
      default_url: /local/images/wallpapers/pexels-victor-freitas-600114.jpg
      entity: weather.openweathermap
      state_url:
        sunny:
          - "https://cdn.flixel.com/flixel/hlhff0h8md4ev0kju5be.hd.mp4"
          - "https://cdn.flixel.com/flixel/zjqsoc6ecqhntpl5vacs.hd.mp4"
          - "https://cdn.flixel.com/flixel/jvw1avupguhfbo11betq.hd.mp4"
          - "https://cdn.flixel.com/flixel/8cmeusxf3pkanai43djs.hd.mp4"
          - "https://cdn.flixel.com/flixel/guwb10mfddctfvwioaex.hd.mp4"
        partlycloudy:
          - "https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4"
          - "https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4"
          - "https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4"
          - "https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4"
          - "https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4"
          - "https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4"
        cloudy:
          - "https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4"
          - "https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4"
          - "https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4"
          - "https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4"
          - "https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4"
          - "https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4"
        mostlycloudy:
          - "https://cdn.flixel.com/flixel/e95h5cqyvhnrk4ytqt4q.hd.mp4"
          - "https://cdn.flixel.com/flixel/l2bjw34wnusyf5q2qq3p.hd.mp4"
          - "https://cdn.flixel.com/flixel/rrgta099ulami3zb9fd2.hd.mp4"
        clear-night:
          - "https://cdn.flixel.com/flixel/x9dr8caygivq5secll7i.hd.mp4"
          - "https://cdn.flixel.com/flixel/v26zyfd6yf0r33s46vpe.hd.mp4"
          - "https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4"
          - "https://cdn.flixel.com/flixel/rosz2gi676xhkiw1ut6i.hd.mp4"
        fog:
          - https://home.eidolf.de/local/weather/Fog-190408_01_Alaska_Landscapes1_09.mp4
          - https://home.eidolf.de/local/weather/Fog-190915_A_01_Timelapse_02.mp4
          - https://home.eidolf.de/local/weather/Fog-Dron_footage_over_a_winter_foggy_mountain.mp4
          - "https://cdn.flixel.com/flixel/vwqzlk4turo2449be9uf.hd.mp4"
          - "https://cdn.flixel.com/flixel/5363uhabodwwrzgnq6vx.hd.mp4"
        rainy:
          - "https://cdn.flixel.com/flixel/f0w23bd0enxur5ff0bxz.hd.mp4"
          - https://home.eidolf.de/local/weather/f0w23bd0enxur5ff0bxz.hd.mp4
          - https://home.eidolf.de/local/weather/Rain-Raindrops_Videvo.mp4
          - https://home.eidolf.de/local/weather/Regen-1.mp4
        pouring:
          - https://home.eidolf.de/local/weather/heavy_rain_in_the_forest.mp4
        snowy:
          - https://home.eidolf.de/local/weather/Snow-2016WinterPrecip_LoopableBackground_1080.mp4
          - https://home.eidolf.de/local/weather/Snow-Day_SnowCoveredTrees.mp4
          - https://home.eidolf.de/local/weather/Snow-Reaviling_Sjusjoen_Ski_Senter.mp4
          - https://home.eidolf.de/local/weather/Snow-Tree-1080p.mp4
          - https://home.eidolf.de/local/weather/Snow-2016FewerColdNights_LoopableBackground_1080.mp4
        snowy-rainy:
          - https://home.eidolf.de/local/weather/Schneeregen_01.mp4
          - https://home.eidolf.de/local/weather/Schneeregen_02.mp4
        lightning-rainy:
          - https://home.eidolf.de/local/weather/Blitz-1.mp4
          - https://home.eidolf.de/local/weather/Blitz-2.mp4
          - https://home.eidolf.de/local/weather/Blitz-3.mp4
          - https://home.eidolf.de/local/weather/Blitz-4.mp4
          - https://home.eidolf.de/local/weather/Blitz-5.mp4
