- id: '1636214178243'
  alias: 'Washer finished cycle '
  description: Notify on phones that washer has finished a cycle.
  trigger:
  - type: turned_on
    platform: device
    device_id: 2f49ef255d2d31d08989070b0c4ef410
    entity_id: binary_sensor.washer_wash_completed
    domain: binary_sensor
  action:
  - service: notify.mobile_app_thomas_phone
    data:
      message: "\U0001F300 De was is klaar! "
  - service: notify.mobile_app_frederieke_iphone
    data:
      message: "\U0001F300 De was is klaar! "
  mode: single
- id: '1653402216389'
  alias: Ring deurbel met oude gong
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door_ding_2
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.front_door_ding
    to: 'on'
  - type: running
    platform: device
    device_id: 59c86400590de25e456588a86b8e5ae5
    entity_id: binary_sensor.doorbell_downstairs_drukker
    domain: binary_sensor
  action:
  - parallel:
    - type: turn_on
      device_id: 59c86400590de25e456588a86b8e5ae5
      entity_id: switch.doorbell_downstairs_gong
      domain: switch
    - service: tts.cloud_say
      data:
        entity_id: media_player.area_aware_media_player
        message: 'Someone at the door! '
        cache: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turn_off
    device_id: 59c86400590de25e456588a86b8e5ae5
    entity_id: switch.doorbell_downstairs_gong
    domain: switch
  mode: single
  max_exceeded: silent
- id: '1653461112548'
  alias: Deurbel Notificatie Thomas
  use_blueprint:
    path: AndreiRadchenko/doorbell-cam-actionable-nitification.yaml
    input:
      notification_title: Iemand aan de deur!
      doorbell_button: siren.gong
      doorbell_cam: camera.front_door_snapshot
      notify_dev: notify.mobile_app_thomas_phone
      uri_: /lovelace/security
- id: '1653554412347'
  alias: Deurbel Notificatie Fre
  use_blueprint:
    path: AndreiRadchenko/doorbell-cam-actionable-nitification.yaml
    input:
      notification_title: Iemand aan de deur!
      doorbell_button: siren.gong
      doorbell_cam: camera.front_door_snapshot
      notify_dev: notify.mobile_app_frederieke_iphone
      uri_: /lovelace/security
- id: '1653934725357'
  alias: Stop media als TV uitgezet wordt
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: bcac3f1fabdc32d269b104756263537f
    entity_id: remote.eetkamer_harmony_hub
    domain: remote
  action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id:
      - media_player.eetkamer
      - media_player.eetkamer_jellyfin
      - media_player.eetkamer_cast
  mode: single
- id: '1657483816969'
  alias: Verlichting uit sleep mode
  description: Haal de verlichting uit sleep mode als sleep mode uit gaat
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.adaptive_lighting_sleep_mode_afzuigkap
      - switch.adaptive_lighting_sleep_mode_bar_hue_plafond
      - switch.adaptive_lighting_sleep_mode_gang_boven
      - switch.adaptive_lighting_sleep_mode_slaapkamer_plafond
      - switch.adaptive_lighting_sleep_mode_trap
      - switch.adaptive_lighting_sleep_mode_woonkamer_tafellamp
      - switch.adaptive_lighting_sleep_mode_woonkamer_plafond
      - switch.adaptive_lighting_sleep_mode_lsc_plafondlampen
      - switch.adaptive_lighting_sleep_mode_woonkamer_bureaulamp
      - switch.adaptive_lighting_sleep_mode_inloopkast_ledstrip
      - switch.adaptive_lighting_sleep_mode_eetkamer_bank_plafond
      - switch.adaptive_lighting_sleep_mode_eetkamer_burealamp
      - switch.adaptive_lighting_sleep_mode_eetkamer_ceiling10_fel
      - switch.adaptive_lighting_sleep_mode_eetkamer_kamerlamp
      - switch.adaptive_lighting_sleep_mode_eetkamer_ceil
  mode: single
- id: '1663018175468'
  alias: Buiten verlichting
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '1'
    id: sunrise
  - platform: sun
    event: sunset
    offset: '-1'
    id: sunset
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: sunrise
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.tuin_lampjes
          - light.tuin_strip
          - light.lsc_stringlight_ww
    - conditions:
      - condition: trigger
        id: sunset
      sequence:
      - service: light.turn_on
        data: {}
        target:
          entity_id:
          - light.tuin_lampjes
          - light.tuin_strip
  mode: single
- id: '1666218976691'
  alias: Cast to Google Hub Bijkeuken
  description: ''
  use_blueprint:
    path: local/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      player: media_player.opslag
      url: http://10.9.8.30:8123/lovelace/opslag
- id: '1666370845576'
  alias: Automatic Theme Change
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: transparent
  mode: single
- id: '1668711755849'
  alias: Tag 2833316 is gescand
  description: ''
  trigger:
  - platform: tag
    tag_id: '2833316'
  - platform: tag
    tag_id: '2868498'
  - platform: tag
    tag_id: '3003698'
  - platform: tag
    tag_id: '3003705'
  condition: []
  action:
  - device_id: b5e7f2ee8aac95350be2575dd67ede17
    domain: mobile_app
    type: notify
    message: 'Test '
  mode: single
- id: '1668984750889'
  alias: Bathroom fan on when light on or humidity above 70
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.thp_bathroom_humidity
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: 70
  - platform: state
    entity_id:
    - light.badkamer
    to: 'on'
    from: 'off'
  condition:
  - condition: state
    entity_id: fan.relais
    state: 'off'
  action:
  - service: fan.turn_on
    data: {}
    target:
      entity_id: fan.relais
  mode: single
- id: '1669029776875'
  alias: Turn Bathroom fan off when humidity < 70 and light is off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.thp_bathroom_humidity
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: 70
  - platform: time_pattern
    minutes: '15'
  condition:
  - condition: state
    entity_id: light.badkamer
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.thp_bathroom_humidity
    below: 70
  action:
  - service: fan.turn_off
    data: {}
    target:
      entity_id: fan.relais
  mode: single
- id: '1669029958958'
  alias: Bathroom switch toggle light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.shelly_1_bathroom_schakelaar
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.shelly_1l_bathroom_lamp
      - light.badkamer
  mode: single
- id: '1669125280981'
  alias: 'Lampen aan als schoonmaakster er is '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.router_e2_14_a0_76_75_63
    to: home
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 20
      kelvin: 4300
      white: 255
    target:
      entity_id: light.alles
  mode: single
- id: '1669466076010'
  alias: Tablets Load Alarm Dashboard
  description: 'Load restricted alarm dashboard on the tablets when alarm is armed. '
  trigger:
  - platform: device
    device_id: 4be213244172f3d3f877c91a0444d2c8
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarm
    type: armed_away
  - platform: device
    device_id: 4be213244172f3d3f877c91a0444d2c8
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarm
    type: armed_night
  condition: []
  action:
  - service: browser_mod.navigate
    data:
      path: /lovelace-alarm
    target:
      device_id:
      - a3fef3295e374b9fba27bb62b9e484c4
  mode: single
- id: '1669466184578'
  alias: Load Tablet start url when alarm disarmed
  description: ''
  trigger:
  - platform: device
    device_id: 4be213244172f3d3f877c91a0444d2c8
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarm
    type: disarmed
  condition: []
  action:
  - service: browser_mod.navigate
    data:
      path: /lovelace/woonkamer
    target:
      device_id:
      - a3fef3295e374b9fba27bb62b9e484c4
  mode: single
- id: '1669496934507'
  alias: Alarm Panel Sounds
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.alarm
    to: pending
  - platform: state
    entity_id:
    - alarm_control_panel.alarm
    to: arming
  condition: []
  action:
  - repeat:
      while:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: arming
      sequence:
      - service: media_player.play_media
        target:
          entity_id: media_player.tablet3
        data:
          media_content_id: media-source://media_source/local/Ring - Sonar.oga
          media_content_type: audio/ogg
        metadata:
          title: Ring - Sonar.oga
          thumbnail:
          media_class: music
          children_media_class:
          navigateIds:
          - {}
          - media_content_type: app
            media_content_id: media-source://media_source
  mode: single
- id: '1669762061493'
  alias: 'Laad Tablets starturl als home assistant opstart '
  description: ''
  trigger:
  - platform: event
    event_type: homeassistant_started
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 25
      milliseconds: 0
  - service: button.press
    data: {}
    target:
      entity_id:
      - button.tablet_1_load_start_url
      - button.tablet_2_load_start_url
      - button.tablet_3_load_start_url_2
  mode: single
- id: '1670060239315'
  alias: 'Badkamer lamp uit '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.shelly_1_bathroom_schakelaar
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.shelly_1l_bathroom_lamp
      - light.badkamer
  mode: single
- id: '1670252084636'
  alias: Verlichting in sleep mode
  description: Als Sleep mode aan gaat, zet dan alle lampen op sleep mode (via adaptive
    lighting op dit moment)
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.adaptive_lighting_sleep_mode_afzuigkap
      - switch.adaptive_lighting_sleep_mode_bar_hue_plafond
      - switch.adaptive_lighting_sleep_mode_gang_boven
      - switch.adaptive_lighting_sleep_mode_slaapkamer_plafond
      - switch.adaptive_lighting_sleep_mode_trap
      - switch.adaptive_lighting_sleep_mode_woonkamer_tafellamp
      - switch.adaptive_lighting_sleep_mode_woonkamer_plafond
      - switch.adaptive_lighting_sleep_mode_lsc_plafondlampen
      - switch.adaptive_lighting_sleep_mode_woonkamer_bureaulamp
      - switch.adaptive_lighting_sleep_mode_inloopkast_ledstrip
      - switch.adaptive_lighting_sleep_mode_eetkamer_bank_plafond
      - switch.adaptive_lighting_sleep_mode_eetkamer_burealamp
      - switch.adaptive_lighting_sleep_mode_eetkamer_kamerlamp
      - switch.adaptive_lighting_sleep_mode_eetkamer_ceiling10_fel
      - switch.adaptive_lighting_sleep_mode_eetkamer_ceil
  mode: single
- id: '1670352454062'
  alias: Radio in de badkamer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.shelly_1_bathroom_schakelaar
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: spotcast.start
    data:
      force_playback: true
      random_song: true
      shuffle: true
      start_volume: 35
      entity_id: media_player.badkamer
      limit: 20
      repeat: context
      offset: 1
      ignore_fully_played: false
  mode: single
- id: '1670354036232'
  alias: 'Stop badkamer muziek als schakelaar uitgaat '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.shelly_1_bathroom_schakelaar
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
      - media_player.badkamer
  mode: single
- id: '1673860979697'
  alias: 'Badkamer media uitschakelen als pauze '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.badkamer
    from: playing
    to: paused
  condition:
  - condition: state
    entity_id: automation.automatisch_muziek_tijdens_het_kakken
    state: 'on'
  action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
      - media_player.badkamer
  mode: single
- id: '1673954749740'
  alias: 'Fontein beneden uit als Sleep mode aan gaat '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.fontein_power
  mode: single
- id: '1673954786431'
  alias: 'Fontein beneden aan als Sleep mode uit gaat '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    to: 'off'
    from: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.fontein_power
  mode: single
- id: '1677082011846'
  alias: 'Notify Thomas als main internet eruit ligt '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.router_gateway_wan_dhcp_status
    from: Online
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_thomas_phone
    data:
      message: 'Glasvezel stukkie, notifying from mobile backup! '
      title: 'Joe! '
  mode: single
- id: '1679570570181'
  alias: 'Sleep mode aan als Fré iPhone Sleep mode '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.frederieke_iphone_focus
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: zone
    entity_id: person.frederieke
    zone: zone.home
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sleep_mode
  mode: single
- id: '1679570632756'
  alias: 'Sleep mode uit als fré iphone sleep mode uit '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.frederieke_iphone_focus
    for:
      hours: 0
      minutes: 0
      seconds: 5
    from: 'on'
    to: 'off'
  condition:
  - condition: zone
    entity_id: person.frederieke
    zone: zone.home
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sleep_mode
  mode: single
- id: '1679579856569'
  alias: Wekker Thomas Events
  description: ''
  use_blueprint:
    path: IATkachenko/full.yaml
    input:
      device: 32bc03e232f39f108ed9a8478be375d0
      person: person.thomas
