title: Thuis
resources: !include resources.yaml
views: !include_dir_merge_list lovelace/
animated_background: !include animated_background.yaml
kiosk_mode:
  user_settings:
    - {users: [Frederieke], hide_header: true, ignore_entity_settings: true}
    - {users: [tablet1],    hide_header: true, ignore_entity_settings: true, hide_sidebar: true}
    - {users: [Thomas],     hide_header: true}
  entity_settings: [{       hide_header: false, entity: {input_boolean.show_header: "on"}}]
