substitutions:
  name: doorbell

esphome:
  name: ${name}-${location}
  friendly_name: "${name} ${location}"
  platform: ESP8266
  board: d1_mini
  project:
    name: zuidwijk.doorbell
    version: "2.0"
captive_portal:

switch:
  - platform: gpio
    pin:
      number: D1
      inverted: false
    name: "gong"
    id: relay
    icon: mdi:alarm-bell

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    name: "drukker"
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      - switch.turn_on: relay
    on_release:
      # On release, turn of the chime.
      - switch.turn_off: relay
