substitutions:
  name: ambilight

esphome:
  name: ${name}-${location}
  friendly_name: "${name} ${location}"
  project:
    name: quinled.dig-uno
    version: "1.3"
captive_portal:

esp8266:
  board: d1_mini
  # framework:
  #   version: 2.7.4

logger:
  hardware_uart: UART1

dallas: [pin: 14]

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO3
    num_leds: "${leds}"
    name: "Leds"
sensor:
  - platform: dallas
    index: 0
    name: "Temperatuur"
