type: vertical-stack
cards:
  - type: custom:alarmo-card
    entity: alarm_control_panel.alarm
    states:
      armed_away:
        hide: false
        button_label: Inschakelen Afwezig                                                      
      armed_night:
        hide: false
        button_label: Inschakelen Nacht
    use_clear_icon: true
    keep_keypad_visible: false
  - type: picture-entity
    entity: binary_sensor.sense_voortuin
    camera_image: camera.03cabcc9_ring_mqtt
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.more_info
        data:
          entity: camera.03cabcc9_ring_mqtt
  - type: picture-entity
    entity: binary_sensor.sense_eetkamer
    camera_image: camera.eetkamera
    camera_view: live
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.more_info
        data:
          entity: camera.eetkamera
  - type: picture-entity
    entity: binary_sensor.sense_keuken
    camera_image: camera.cat_cam
    camera_view: live
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.more_info
        data:
          entity: camera.cat_cam
  - type: picture-entity
    entity: binary_sensor.sense_woonkamer
    camera_image: camera.woonkamer_tablet
    camera_view: live
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.more_info
        data:
          entity: camera.woonkamer_tablet