substitutions:
  location: kitchen
  
packages:
  defaults: !include includes/defaults.yaml
  device:   !include includes/bluetooth-hub.yaml
  sensor:   !include includes/nfc.yaml

wifi:
  use_address: 10.9.8.16