substitutions:
  location: office

packages:
  defaults: !include includes/defaults.yaml
  device: !include includes/lsc-ceiling-light-sm2135.yaml
  board: !include includes/tuya-cbcl5.yaml

wifi:
  use_address: 10.9.8.130
