substitutions:
  location: diningroom
  
packages:
  defaults: !include includes/defaults.yaml
  blehub:   !include includes/bluetooth-hub.yaml
  # plants:   !include includes/plants.yaml

uart:
  rx_pin: GPIO10
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "${location} Particulate Matter 2.5µm Concentration"
