substitutions:
  location: kitchen

packages:
  defaults: !include includes/defaults.yaml
  device: !include includes/lsc-ceiling-light-sm2135.yaml
  board: !include includes/tuya-wbcl5.yaml

# wifi:
#   use_address: 10.9.8.65
