sensor:
  - platform: template
    sensors:
      count_lights_on:
        friendly_name: "# Lights on"
        value_template: >
          {{ states.light
            | selectattr('state', 'eq', 'on') 
            | rejectattr('object_id', 'search', '^browser_') 
            | rejectattr('attributes.is_hue_group', 'eq', true) 
            | rejectattr('attributes.entity_id', 'defined') 
            | list 
            | count 
          }}
  - platform: template
    sensors:
      count_media_on:
        friendly_name: "# media on"
        unit_of_measurement: "spelend"
        value_template: >
          {{ states.media_player
            | rejectattr('state', 'eq', 'off')
            | rejectattr('state', 'eq', 'idle')
            | rejectattr('object_id', 'search', '^mass_')
            | rejectattr('object_id', 'search', '^browser_') 
            | list 
            | count 
          }}