sensor:
  - platform: template
    sensors:
      count_lights_on:
        friendly_name: "# Lights on"
        value_template: >
          {{ states.light
            | selectattr('state', 'eq', 'on')
            | rejectattr('object_id', 'search', '_screen^')
            | rejectattr('attributes.is_hue_group', 'eq', true)
            | rejectattr('attributes.entity_id', 'defined')
            | list 
            | count 
          }}