emulated_hue: # for harmony home control buttons
  expose_by_default: false
  entities:
    light.diningroom_ceiling10_night_light:
      name: "Eetkamer plafond"
      hidden: false
    light.dining_corner:
      name: "Eetkamer corner lamp"
      hidden: false
    light.dining_sofa_ceiling:
      name: "Eetkamer corner plafond"
      hidden: false
    light.hoek:
      name: "Eetkamer vloerlamp"
      hidden: false
    light.lavalamp:
      name: "Lavalamp"
      hidden: false

## mediaplayer woonkamer ################################
binary_sensor:
  - platform: ping
    host: 10.9.8.59
    name: Mi TV Woonkamer
    count: 1
    scan_interval: 15
switch:
  - platform: wake_on_lan
    mac: d4:5e:ec:95:5b:48
    name: Mi TV Woonkamer
    host: 10.9.8.59
    broadcast_address: 10.9.8.255
media_player:
  # android tv & cast integrations are setup using the ui
  # media_player.android_tv_10_9_8_59
  # media_player.woonkamer_cast
  - platform: universal
    name: woonkamer
    friendly_name: TV
    children:
      - media_player.woonkamer_jellyfin
      - media_player.mass_woonkamer_cast
      - media_player.woonkamer_cast
      - media_player.android_tv_10_9_8_59
     # - media_player.woonkamer_tablet
    commands:
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.mi_tv_woonkamer
  #########################################################
  - platform: universal
    name: eetkamer
    children:
      - media_player.eetkamer_jellyfin
      - media_player.mass_eetkamer_cast
      - media_player.eetkamer_cast
      - media_player.android_tv_10_9_8_37
  ### Global
  - platform: universal
    name: global
    children:
      - media_player.home
      - media_player.woonkamer
      - media_player.mass_slaapkamer
      - media_player.slaapkamer
      - media_player.eetkamer
      - media_player.mass_keuken
      - media_player.keuken
      - media_player.mass_badkamer
      - media_player.badkamer
      - media_player.mass_storage
      - media_player.storage
  - platform: universal
    name: slaapkamer
    children:
      - media_player.slaapkamer_jellyfin
      - media_player.mass_slaapkamer_cast
      - media_player.slaapkamer_cast
      - media_player.android_tv_10_9_8_122