
binary_sensor:
  # beweging per kamer
  - platform: group
    name: "beweging woonkamer"
    device_class: motion
    entities:
      - binary_sensor.woonkamer_pir_occupancy
  - platform: group
    name: "beweging inloopkast"
    device_class: motion
    entities:
      - binary_sensor.inloopkast_pir_occupancy
  - platform: group
    name: "beweging badkamer"
    device_class: motion
    entities:
      - binary_sensor.pir_bathroom_occupancy
  - platform: group
    name: "beweging keuken"
    device_class: motion
    entities:
      - binary_sensor.beweging_keuken_tablet
  - platform: group
    name: "beweging trap"
    device_class: motion
    entities:
      - binary_sensor.pir_stairs_occupancy
  - platform: group
    name: "beweging voortuin"
    device_class: motion
    entities:
      - binary_sensor.front_door_motion
      - binary_sensor.front_door_motion_2
  # deuren per kamer
  - platform: group
    name: "deuren voortuin"
    device_class: door
    entities:
      - binary_sensor.voordeur_contact
  - platform: group
    name: "deuren bar"
    device_class: door
    entities:
      - binary_sensor.hordeur_contact
  - platform: group
    name: "deuren tuin"
    device_class: door
    entities:
      - binary_sensor.tuindeur_contact
  - platform: group
    name: "deuren washok"
    device_class: door
    entities:
      - binary_sensor.laundry_door_contact
  # room active (is there motion, a door open, media playing)
  - platform: group
    name: "sense woonkamer"
    device_class: occupancy
    entities:
      - binary_sensor.beweging_woonkamer
  - platform: group
    name: "sense bar"
    device_class: occupancy
    entities:
      - binary_sensor.deuren_bar
  - platform: group
    name: "sense keuken"
    device_class: occupancy
    entities:
      - binary_sensor.beweging_keuken
  - platform: group
    name: "sense tuin"
    device_class: occupancy
    entities:
      - binary_sensor.deuren_tuin
  - platform: group
    name: "sense voortuin"
    device_class: occupancy
    entities:
      - binary_sensor.beweging_voortuin
      - binary_sensor.deuren_voortuin
  - platform: group
    name: "sense trap"
    device_class: occupancy
    entities:
      - binary_sensor.beweging_trap
      - binary_sensor.deuren_voortuin
  - platform: group
    name: "sense inloopkast"
    device_class: occupancy
    entities:
      - binary_sensor.beweging_inloopkast
  - platform: group
    name: "sense washok"
    device_class: occupancy
    entities:
      - binary_sensor.deuren_washok
  - platform: group
    name: "sense eetkamer"
    device_class: occupancy
    entities:
      - binary_sensor.motion_eetkamera
