- type: custom:mushroom-alarm-control-panel-card
  entity: alarm_control_panel.alarm
  states:
    - armed_home
    - armed_away
    - armed_night
  name: ' '
  layout: vertical
  show_keypad: true
  view_layout:
    grid-column: auto / span 2
    grid-row: auto / span 2
- type: picture-entity
  entity: binary_sensor.sense_voortuin
  camera_image: camera.03cabcc9_ring_mqtt
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.more_info
      data:
        entity: camera.03cabcc9_ring_mqtt
  name: Voordeur
  view_layout:
    grid-column: auto / span 2
    grid-row: auto / span 3
- type: picture-entity
  view_layout:
    grid-column: auto / span 2
    grid-row: auto / span 3
  entity: binary_sensor.sense_eetkamer
  camera_image: camera.eetkamera
  camera_view: live
  name: Eetkamer
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.more_info
      data:
        entity: camera.eetkamera
  hold_action:
    action: navigate
    navigation_path: /lovelace/eetkamer
- type: conditional
  view_layout:
    grid-column: auto / span 2
    grid-row: auto / span 3
  conditions:
    - entity: binary_sensor.tablet1_plugged_in
      state: "on"
  card:
    type: picture-entity
    entity: binary_sensor.sense_tablet1
    camera_image: camera.tablet1
    camera_view: live
    name: Tablet 1
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.more_info
        data:
          entity: camera.tablet1
- type: picture-entity
  view_layout:
    grid-column: auto / span 2
    grid-row: auto / span 3
  entity: binary_sensor.sense_keuken
  camera_image: camera.cat_cam
  camera_view: live
  name: Keuken
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.more_info
      data:
        entity: camera.cat_cam
  hold_action:
    action: navigate
    navigation_path: /lovelace/keuken
